### ISSUE TITLE
Metody dla PHP

### ISSUE THREAD

**Issue by harpersoft** [Teleinformatyka/RedSparrow#56]
*metoda zmieniająca daną wartość w tabeli 
      @param: key - nazwa kolumny, value - wartość, id - id pracy
*usuwanie pracy
     @param: id - id pracy
*edycja profilu
      @param: key - nazwa kolumny, value - wartość, id - id usera
*usuwanie użytkownika
      @param: id - id użytkownika
*edytowanie i usuwanie wyników analizy prac

**Comment by Aldor007** [comment]
https://github.com/Teleinformatyka/RedSparrow/blob/master/redsparrow/methods/front.py#L207 metody które mają self.user nie będą działać
